### ISSUE TITLE
HW Dependencies and Custom AKA Authentication

### ISSUE THREAD

**Issue by Vomvas** [tomasz-lisowski/swsim#11]
Hello,

Thank you very much for your contribution, this is very useful!

Just to verify, if I need to use the swSIM with an actual phone I will need some HW, such as the [sysmoQMOD](https://shop.sysmocom.de/sysmoQMOD-evaluation-kit/sysmoQMOD-evk), right? The "no HW dependency" refers to the swSIM itself, in order to program it?

Also, I was able to find the Comp128 implementation for GMS, is this tested for Milenage in  LTE? Is it possible to add my custom version of `run_my_auth_algo` so that it gets invoked during 5G_AKA?

Thanks,
Marinos

**Comment by tomasz-lisowski** [comment]
Thanks for the kind words :>.

As for hardware, yes if you'd like to connect swSIM to a real device, I'd probably recommend [SIMTrace2](https://shop.sysmocom.de/SIMtrace2-Hardware-Kit/simtrace2-kit) running on the cardemu firmware, as that is what I used.

swSIM was designed to support research into emulated mobile basebands. Due to time constraints and a lack of hardware, I was not able to test even the GSM authentication for correctness. I included the code anyways in hopes others with hardware and time, would report back and contribute to the project.

As for 5G, it is of course possible to add the newer authentication algorithms. The USIM application does not use the GSM AUTHENTICATE instruction (for which I provided the aforementioned prototype), rather it uses ETSI TS 102 221 AUTHENTICATE (and probably GET CHALLENGE). This means that in order to begin implementing newer authentication algorithms, you'll first need to implement an APDU handler for the ETSI AUTHENTICATE instruction (`sim_apduh_demux` inside `src/apduh.c` does the demuxing to decide what APDU handler to run, so you can add a call to your function in the correct place inside that switch).
For details on the AKA process, I would look into ETSI TS 133 501 (e.g. section 6.1.3.1) and some parts of 3GPP TS 31.102. I'm not very familiar with the AKA procedure so I don't know how else to help.

I hope this helps, but feel free to ask more questions and/or make pull requests along the way :).

**Comment by Vomvas** [comment]
Hello Tomasz,

Thanks for the clarification and the tips about the APDU handler and the 5G AKA, they're very helpful!

One small follow up: when you mention emulated basebands, are you referring to stacks such as the srsUE and UERANSIM, or something else that can run on a real phone?

**Comment by tomasz-lisowski** [comment]
I was referring to baseband emulation with [FirmWire](https://github.com/FirmWire/FirmWire) :)
