### ISSUE TITLE
Undefined Instruction while communicating with modem (Quectel EC25)

### ISSUE THREAD

**Issue by mike0609king** [tomasz-lisowski/swsim#15]
## Setup
swSIM is used with simtrace2, which forwards the traffic to the Quectel EC25.

## Problem
I am tring to lock onto a LTE cell with the modem (using the AT+QNWLOCK command). The modem doesn't lock onto the cell. It looks like the modem sends commands to the swSIM that are not defined. I have attached the [output of simtrace](https://github.com/tomasz-lisowski/swsim/files/15170403/simtrace2_output.txt) and the [recorded PCAP](https://github.com/tomasz-lisowski/swsim/files/15170426/pcap.zip) (in a zip-file).

## Questions
- Is this a bug or is the functionality not implemented?
- It it isn't implemented: Do you have the time to do so?
- If you don't have the time to do so: Do you have suggestions about how one can implement it?

**Comment by tomasz-lisowski** [comment]
I added the missing `UPDATE RECORD` instruction in d828304d9676fdf449135dd2d38ae01c268a160d. This *might* solve your problem.

**Comment by mike0609king** [comment]
`UPDATE RECORD` seems to work perfectly now, but `ENVELOPE Call Control` also seems to be undefined. Could this cause a problem too?
![image](https://github.com/tomasz-lisowski/swsim/assets/57289368/a31e8117-3c52-4a9b-bc6d-b1319d25210f)

**Comment by tomasz-lisowski** [comment]
I doubt the call control instruction is mandatory for it to work. Please keep me posted though, I could be wrong.

**Comment by mike0609king** [comment]
I also thought that the `ENVELOPE` command as a whole is optional. I managed to modify swSIM such that it would return the status code 9000, when the program sees the `ENVELOPE` command. This fixes the issue, but I don't know why :(.

Is it possible for you to return 9000 whenever an `ENVELOPE` command is given or would it cause some weird bugs?

**Comment by tomasz-lisowski** [comment]
CAT (i.e. card application toolkit) is normally optional since not all SIM cards support the proactive features of CAT as described in ETSI TS 102 223.

I incorrectly set the "call control" service as supported in the UST (USIM service table). Call control service has number 30 in the EF.UST (FID=`6F38`) per ETSI TS 131 102. If you want the modem to not send any CAT commands, it is best to set all related services to unsupported (=0). 
Old UST with call control: `BEFFBF9DE73E0408400170730000002E00000000`
New UST without call control: `BEFFBF99E73E0408400170730000002E00000000`

I will do a deeper look at the UST to see how it should look given the features of swSIM. Most of the files in `data/usim.json` have been copied directly from an existing Sysmocom card and may not contain exactly the right data. I will look into generating these files in the future, right now I don't have enough time to manually check every single bit of every single file. :/

Hope this helps.

**Comment by tomasz-lisowski** [comment]
In regards to if sending `9000` in response to the call control `ENVELOPE`:

In your case, since this is a call control message, it forces the modem to send all dialled numbers, USSD, etc. to pass through the SIM, allowing the card to modify, bar, or allow the call to happen. More details are described in ETSI TS 131 111.

Per ETSI TS 131 111 clause 7.3.1.6, `It is permissible for the UICC to provide no response data, by responding with SW1/SW2 = '90 00'`. So no, sending `9000` will not cause any problems.

Just remember that not all `ENVELOPE` commands are for call control, so not all of them allow a plain `9000` response. You'll need to monitor the commands in case some other `ENVELOPE` is sent.

**Comment by mike0609king** [comment]
Thanks a lot! Your comments were extremely helpful :D
