### ISSUE TITLE
There is an inaccuracy in the file "./data/gsm.json"

### ISSUE THREAD

**Issue by edbek** [tomasz-lisowski/swsim#3]
There is an inaccuracy in the file "./data/gsm.json":

1. identifier "id" of the file for "EXT3" ("name": "Extension 3") is equal to "6F4B" instead of "6F4C"

2. in addition, the files "LND" ("id": "6F44") and "Accumulated call meter" ("id": "6F39") are designated as "file_ef_linear-fixed", although according to the standard they should be as "file_ef_cyclic". Does it matter or will it work as is?

**Comment by tomasz-lisowski** [comment]
Hey. Thanks for pointing out the inaccuracies! There are so many files in both the GSM and USIM file systems (with many of them optional) that it's hard to test the correctness of it all, especially if things appear to be working correctly in the tests I've done. 

As for the LND and ACM files, I was not able to find a device which utilized these files (making it hard to do testing), but most likely (due to how record selection works), they would not work correctly as fixed linear files.

I fixed the files you're referring to in 02c952955b8c8ed0eba3a61967ce19f79de0788b.
